{
 "title": "Airquality",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "temp.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "humidity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "format": "humidity",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "temperature graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "3" ], "type": "top" }
      ]
     ]
    }
   ]
  },
  {
   "title": "humidity graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "3" ], "type": "top" }
      ]
     ]
    }
   ]
  },
  {
   "title": "pressure graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "pressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "3" ], "type": "top" }
      ]
     ]
    }
   ]
  }
 ]
}