---
- name: Create influxdb database
  influxdb_database:
    database_name: "airquality"
- name: clone airquality repo
  git: >
      repo=https://github.com/rbabyuk/air_quality.git
      dest=/home/pi/air_quality
- name: create crontab entry for airquality script
  cron:
    name: "airquality job"
    minute: "*/2"
    user: pi
    job: "/home/pi/air_quality/air_quality.py"
